### ISSUE TITLE
Peer operation failure leads to cascading failures and eventual TC framework failure

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#235]
Now I can understand a failure in a test case as an indication of bug in the product, but the testing framework should handle the exception and move on to the next test case rather than getting bogged down and eventually giving up. For example,

```
Traceback (most recent call last):
  File "./core/redant_main.py", line 99, in <module>
    main()
  File "./core/redant_main.py", line 87, in main
    result_queue = TestRunner.run_tests()
  File "/root/redant-files/redant/core/test_runner.py", line 61, in run_tests
    cls._run_test(test)
  File "/root/redant-files/redant/core/test_runner.py", line 94, in _run_test
    runner_thread_obj = RunnerThread(tc_class, cls.param_obj,
  File "/root/redant-files/redant/core/runner_thread.py", line 17, in __init__
    self.tc_obj = tc_class(mname, param_obj, volume_type,
  File "./tests/parent_test.py", line 48, in __init__
    self.redant.create_cluster(self.server_list)
  File "./common/ops/gluster_ops/peer_ops.py", line 221, in create_cluster
    self.delete_cluster(temp_cluster)
  File "./common/ops/gluster_ops/peer_ops.py", line 249, in delete_cluster
    self.peer_detach(nd, node)
  File "./common/ops/gluster_ops/peer_ops.py", line 66, in peer_detach
    ret = self.execute_abstract_op_node(cmd, node)
  File "./common/ops/abstract_ops.py", line 37, in execute_abstract_op_node
    raise Exception(ret['msg']['opErrstr'])
Exception: <sample_ip> is not part of cluster
```

This inturn implies that the peer ops is not handling all the possible return values after a peer probe.

**Comment by srijan-sivakumar** [comment]
Resurfaced...

```
  9 [2021-05-06 18:19:25,584] DEBUG  - {'msg': {'opRet': '0', 'opErrno': '0', 'opErrstr': None, 'peerStatus': {'peer': [{'uuid': '3228e718-ac03-43b1-a945-1f2fddac2df4', 'hostname': 'dhcp43-1    75.lab.eng.blr.redhat.com', 'hostnames': {'hostname': 'dhcp43-175.lab.eng.blr.redhat.com'}, 'connected': '1', 'state': '6', 'stateStr': 'Peer Rejected'}, {'uuid': '35511672-dfe0-475a-a25    9-74fb9c766998', 'hostname': '10.70.43.162', 'hostnames': {'hostname': '10.70.43.162'}, 'connected': '1', 'state': '3', 'stateStr': 'Peer in Cluster'}, {'uuid': '5f73597e-6a3b-4523-94d1-    39e46a722ff5', 'hostname': 'localhost', 'connected': '1'}]}}, 'Flag': True, 'node': '10.70.42.220', 'cmd': 'gluster pool list --xml', 'error_code': 0}
```

The state will be 3 if peering is a success and 6 stands for rejection. We should fail the operation if state is anything other than 3 in case of peer probe.

**Comment by srijan-sivakumar** [comment]
@nishith-vihar ^^
