### ISSUE TITLE
Nd_Parent_test: reset volume options fails

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/redant#370]
While running a test case, I encountered an error regarding the reset volume options. 
There are certain volume options that occur for all the volumes and not a specific volume. 
For ex:
In this test there was a volume option cluster.server-quorum-ratio set to 70 percent which went successful as it was executed on all volumes but when it came to the reset part in the nd_parent_test it was getting reset volume wise.

```log
[2021-05-18 19:20:30,024] INFO  - Running gluster vol reset redant-rep cluster.server-quorum-ratio --mode=script --xml on 10.70.43.74
[2021-05-18 19:20:30,275] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'Not a valid option for single volume', 'cliOp': 'volReset', 'output': 'Not a valid option for single volume'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster vol reset redant-rep cluster.server-quorum-ratio --mode=script --xml', 'error_code': 0}
[2021-05-18 19:20:30,275] ERROR  - Not a valid option for single volume
[2021-05-18 19:20:30,276] ERROR  - Not a valid option for single volume
[2021-05-18 19:20:30,276] ERROR  - Traceback (most recent call last):
  File "./tests/nd_parent_test.py", line 90, in terminate
    self.redant.reset_volume_option(self.vol_name, opt,
  File "./common/ops/gluster_ops/volume_ops.py", line 631, in reset_volume_option
    ret = self.execute_abstract_op_node(cmd, node)
  File "./common/ops/abstract_ops.py", line 39, in execute_abstract_op_node
    raise Exception(ret['msg']['opErrstr'])
Exception: Not a valid option for single volume
```

We need to check if it is a volume `all` option and then send the reset volume option the correct params?

_Originally posted by @aujjwal-redhat in https://github.com/srijan-sivakumar/redant/discussions/368_

**Comment by aujjwal-redhat** [comment]
Apparently, this might not be an issue as the scenario won't come in non-disruptive situations.
