### ISSUE TITLE
Exception thrown in xls mandated output

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#727]
```python
Traceback (most recent call last):
  File "./core/redant_main.py", line 139, in <module>
    main()
  File "./core/redant_main.py", line 131, in main
    ResultHandler.handle_results(
  File "/root/redant-files/redant/core/result_handler.py", line 274, in handle_results
    cls.store_results_in_excelsheet(
  File "/root/redant-files/redant/core/result_handler.py", line 230, in store_results_in_excelsheet
    result_sheet.write(row, 3, each_vol_test['skipReason'])
  File "/root/redant-files/rvirt/lib/python3.8/site-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/root/redant-files/rvirt/lib/python3.8/site-packages/xlwt/Row.py", line 254, in write
    raise Exception("Unexpected data type %r" % type(label))
Exception: Unexpected data type <class 'Exception'>
```

**Comment by srijan-sivakumar** [comment]
This CI result was obtained in old code. Have to check if the issue persists in the latest code.
